#ifndef OLLAMACLIENT_H
#define OLLAMACLIENT_H

#include <string>
#include <stdexcept>

/// @brief Exception thrown when communication with Ollama fails.
class OllamaConnectionException : public std::runtime_error {
public:
    explicit OllamaConnectionException(const std::string& msg) : std::runtime_error(msg) {}
};

/// @brief Handles REST API communication with a local Ollama instance.
class OllamaClient {
public:
    /// @brief Constructor
    /// @param baseUrl The base URL of the Ollama API, e.g., "http://localhost:11434"
    explicit OllamaClient(const std::string& baseUrl = "http://localhost:11434");

    /// @brief Generates a command via Ollama completion API.
    /// @param systemContext System prompt giving constraints to the AI.
    /// @param userPrompt The natural language user request.
    /// @return Raw command string generated by the LLM.
    /// @throws OllamaConnectionException if API call fails or JSON is invalid.
    std::string generateCommand(const std::string& systemContext, const std::string& userPrompt);

private:
    std::string m_baseUrl;
    
    /// @brief LibCURL write callback to append received data.
    static size_t WriteCallback(void* contents, size_t size, size_t nmemb, void* userp);
};

#endif // OLLAMACLIENT_H
